version: '3.7'

services:
  rl_coach:
    logging:
      driver: awslogs
      options:
        awslogs-group: '/local/deepracer-for-cloud/rl_coach'
        awslogs-create-group: 'true'
        awslogs-region: ${DR_AWS_APP_REGION}
        tag: "${DR_CLOUD_WATCH_LOG_STREAM_PREFIX}{{.Name}}"
  robomaker:
    logging:
      driver: awslogs
      options:
        awslogs-group: '/local/deepracer-for-cloud/robomaker'
        awslogs-create-group: 'true' 
        awslogs-region: ${DR_AWS_APP_REGION}
        tag: "${DR_CLOUD_WATCH_LOG_STREAM_PREFIX}{{.Name}}"