MAX_SPEED = 4.0
ABS_MAX_STEERING_ANGLE = 30
MIN_SPEED = 1.99
FPS = 15
MAX_SPEED_DIFF = MAX_SPEED - 0
SEGMENT_ANGLE_THRESHOLD = 5
CURVE_ANGLE_THRESHOLD = 70
CURVE_DISTANCE_RATIO_THRESHOLD = 1
MAX_HEADING_ERROR = 90
WAYPOINT_LOOKAHEAD_DISTANCE = 1
LOOKAHEAD_TRACK_WIDTH_FACTOR = 1

INF = float('inf')
NINF = -INF